"""empty message

Revision ID: ba8f40963cfe
Revises: 750e18ed8a06
Create Date: 2022-02-08 23:14:39.877205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba8f40963cfe'
down_revision = '750e18ed8a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dislikes', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('dislikes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dislikes', 'comment')
    op.alter_column('likes', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('likes', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('dislikes', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('dislikes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dislikes', 'posted_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
